nodes:
  - address: xxx.xx.xx.xxx #private IP of Rancher Server
    internal_address: xxx.xx.xx.xxx #private IP of Rancher Server
    user: ubuntu
    role: [controlplane, worker, etcd]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

ssh_key_path: ~/.ssh/kzs61-rancher.key

# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"